/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    students: StudentAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    modules: Module;
    lessons: Lesson;
    users: User;
    students: Student;
    progress: Progress;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    progress: ProgressSelect<false> | ProgressSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    plans: Plan;
  };
  globalsSelect: {
    plans: PlansSelect<false> | PlansSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Student;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface StudentAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  name: string;
  /**
   * Совпадает с App.COURSES[].id на сайте. Менять только вместе с кодом сайта.
   */
  slug: 'base' | 'oge';
  short: string;
  kicker?: string | null;
  note?: string | null;
  /**
   * Меньше число — выше в интерфейсе
   */
  order: number;
  /**
   * Считается при импорте и проверке (pnpm verify)
   */
  lessonsCount?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  order: number;
  course: number | Course;
  /**
   * Например 1, 13.1, 14 или «все» для диагностики
   */
  exam?: string | null;
  ball?: number | null;
  hours?: number | null;
  /**
   * Что ученик умеет после модуля — попадает в уроки и в промпт провожатого
   */
  goal?: string | null;
  engine?: ('sandbox' | 'code' | 'robot' | 'sql' | 'table' | 'graph') | null;
  mode?: ('sim' | 'download' | 'real' | 'exam') | null;
  /**
   * Критерий «модуль закрыт» из шаблона курса
   */
  check?: string | null;
  /**
   * Связь «задание ОГЭ → уроки базового курса» (поле base в реестре)
   */
  baseLessons?:
    | {
        n: number;
        id?: string | null;
      }[]
    | null;
  gap?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  downloads?:
    | {
        title: string;
        kind?: ('tool' | 'data' | 'sample') | null;
        mb?: number | null;
        url?: string | null;
        why?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Правило курса: практические задания несколько раз делаются в настоящей программе
   */
  realMinimum?: {
    runs?: number | null;
    timed?: number | null;
    what?: string | null;
  };
  simLimit?: string | null;
  lessonsCount?: number | null;
  /**
   * Не путать с черновиком Payload (versions/drafts): это готовность материала
   */
  contentStatus?: ('каркас' | 'черновик' | 'готов') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * 1–300 школьный курс, 1001–1100 курс ОГЭ. Менять нельзя: по нему считается прогресс ученика
   */
  siteId: number;
  title: string;
  sub?: string | null;
  course: number | Course;
  module: number | Module;
  kind: 'lesson' | 'practice' | 'exam';
  minutes?: number | null;
  order?: number | null;
  /**
   * Разметка как на сайте: **жирный**, `код`, строки «> Лайфхак.» и «!! Ошибка.», блок ~~~ для примеров
   */
  theory?: string | null;
  tasks?:
    | {
        /**
         * Например l1t1 — ключ ответа ученика в браузере
         */
        tid: string;
        type?: ('input' | 'choice') | null;
        /**
         * Для выбора — номер варианта с нуля. Альтернативы разделяются символом |
         */
        answer: string;
        q: string;
        options?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        explain: string;
        id?: string | null;
      }[]
    | null;
  practice?: {
    engine: 'sandbox' | 'code' | 'robot' | 'sql' | 'table' | 'graph';
    brief?: string | null;
    /**
     * Тот же объект, что ждёт App.PRACTICE.<engine>.mount(host, cfg, ctx)
     */
    config?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  oge?: {
    exam?: string | null;
    mode?: ('sim' | 'download' | 'real' | 'exam') | null;
    ball?: number | null;
    files?:
      | {
          title: string;
          size?: string | null;
          url?: string | null;
          why?: string | null;
          id?: string | null;
        }[]
      | null;
    realRuns?: number | null;
    realTimed?: number | null;
    shortTrack?: boolean | null;
    simLimit?: string | null;
    check?: string | null;
    goal?: string | null;
  };
  /**
   * Не путать с черновиком Payload: это готовность материала
   */
  contentStatus?: ('каркас' | 'черновик' | 'готов') | null;
  /**
   * Файл, из которого урок импортирован (для сверки)
   */
  sourceFile?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Вход в админку. Контент курсов, ученики, тарифы, письма.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Роль admin открывает всё; editor — только курсы, модули, уроки, медиа
   */
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Аккаунты сайта: вход по почте и паролю, подтверждение почты, сброс пароля.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  name?: string | null;
  grade?: ('7' | '8' | '9' | 'other') | null;
  course?: ('oge' | 'base' | 'both') | null;
  /**
   * Тариф ученика в базе — по нему сервер решает, пускать ли к провожатому (/api/ai). Клиентская проверка нужна для интерфейса, но обойти её нельзя: решает сервер. Значение по умолчанию — «Максимум»: ученики, созданные до появления поля, не теряют доступ.
   */
  plan?: ('free' | 'full' | 'max') | null;
  /**
   * Регистрируясь, ученик (или родитель) соглашается на хранение прогресса
   */
  consent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'students';
}
/**
 * Ответы, пройденные уроки и серии дней. Сайт синхронизирует сюда localStorage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress".
 */
export interface Progress {
  id: number;
  /**
   * Один документ на ученика
   */
  student: number | Student;
  /**
   * Объект вида { "12": { "at": 1700000000000 } } — как в localStorage сайта
   */
  completed?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Объект вида { "l1t1": { ok: true, v: "2", at: … } }
   */
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  practice?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  test?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  streak?: number | null;
  minutes?: number | null;
  /**
   * Например: сайт, браузер Chrome, перенос из localStorage
   */
  source?: string | null;
  /**
   * Объект вида { "2026-09-21": { tokens: 41200, calls: 9 } }. Считает сервер (/api/ai), чтобы ключ DeepSeek не лежал в браузере и лимит нельзя было обойти.
   */
  aiUsage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Например: hero — главная; lesson — картинка урока; greet — озвучка приветствия
   */
  usage?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'progress';
        value: number | Progress;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'students';
        value: number | Student;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'students';
        value: number | Student;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  short?: T;
  kicker?: T;
  note?: T;
  order?: T;
  lessonsCount?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  course?: T;
  exam?: T;
  ball?: T;
  hours?: T;
  goal?: T;
  engine?: T;
  mode?: T;
  check?: T;
  baseLessons?:
    | T
    | {
        n?: T;
        id?: T;
      };
  gap?:
    | T
    | {
        text?: T;
        id?: T;
      };
  downloads?:
    | T
    | {
        title?: T;
        kind?: T;
        mb?: T;
        url?: T;
        why?: T;
        id?: T;
      };
  realMinimum?:
    | T
    | {
        runs?: T;
        timed?: T;
        what?: T;
      };
  simLimit?: T;
  lessonsCount?: T;
  contentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  siteId?: T;
  title?: T;
  sub?: T;
  course?: T;
  module?: T;
  kind?: T;
  minutes?: T;
  order?: T;
  theory?: T;
  tasks?:
    | T
    | {
        tid?: T;
        type?: T;
        answer?: T;
        q?: T;
        options?:
          | T
          | {
              text?: T;
              id?: T;
            };
        explain?: T;
        id?: T;
      };
  practice?:
    | T
    | {
        engine?: T;
        brief?: T;
        config?: T;
      };
  oge?:
    | T
    | {
        exam?: T;
        mode?: T;
        ball?: T;
        files?:
          | T
          | {
              title?: T;
              size?: T;
              url?: T;
              why?: T;
              id?: T;
            };
        realRuns?: T;
        realTimed?: T;
        shortTrack?: T;
        simLimit?: T;
        check?: T;
        goal?: T;
      };
  contentStatus?: T;
  sourceFile?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  name?: T;
  grade?: T;
  course?: T;
  plan?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress_select".
 */
export interface ProgressSelect<T extends boolean = true> {
  student?: T;
  completed?: T;
  answers?: T;
  practice?: T;
  test?: T;
  streak?: T;
  minutes?: T;
  source?: T;
  aiUsage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  usage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  items?:
    | {
        planId: string;
        name: string;
        price?: number | null;
        /**
         * Если выключено — режимы трат закрыты, кружок лимита показывает прочерк
         */
        ai?: boolean | null;
        dailyTokens?: number | null;
        badge?: string | null;
        /**
         * Заполняется только у тарифов с нейронкой: eco, std, pro
         */
        modes?:
          | {
              mode: string;
              id?: string | null;
            }[]
          | null;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  promoCodes?:
    | {
        code: string;
        plan: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  items?:
    | T
    | {
        planId?: T;
        name?: T;
        price?: T;
        ai?: T;
        dailyTokens?: T;
        badge?: T;
        modes?:
          | T
          | {
              mode?: T;
              id?: T;
            };
        desc?: T;
        id?: T;
      };
  promoCodes?:
    | T
    | {
        code?: T;
        plan?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}